import Head from 'next/head'
import { Curating, Popular, Recommend, Box } from '@/components'

import {
  ICurating,
  IPopular,
  IProductTab,
  IRecommend,
} from '@/pages/api/products'

// import request from '@/service/http'

import ProductTabCarousel from '@/components/ProductTabCarousel'
import Layout from '@/components/layout/layout'

export async function getServerSideProps() {
  // let data

  // try {
  //   data = await request<ProductsProp>('/products')
  // } catch (error: any) {
  //   return {
  //     props: {
  //       error: {
  //         statusCode: 500,
  //         message: JSON.stringify(error.message),
  //       },
  //     },
  //   }
  // }

  const datas = require('/public/datas/curating.json')

  return {
    props: {
      ...datas,
    },
  }
}

interface ProductsProp {
  tabList: IProductTab[]
  newBdg: string[]
  pdRcmdFavSvrList1: ICurating[]
  pdRcmdFavSvrList2: IPopular[]
  pdRcmdFavSvrList3: IRecommend[]
}

// Next.js 12에서는 Page 단위로 데이터 페칭이 가능하다.
// Next.js 13부터 컴포넌트 단위로 데이터 페칭이 가능하다.

export default function ProductsPage({
  tabList,
  newBdg,
  pdRcmdFavSvrList1,
  pdRcmdFavSvrList2,
  pdRcmdFavSvrList3,
}: ProductsProp) {
  return (
    <Layout>
      <Head>
        <title>상품 - 케이뱅크</title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <meta charSet="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="pragma" content="no-cache" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0"
        />
        <meta
          name="description"
          content="제1금융권 1호 인터넷전문은행 케이뱅크"
        />
        <meta
          name="format-detection"
          content="telephone=no, address=no, email=no"
        />
        <meta
          property="og:url"
          content="https://m.kbanknow.com/ib20/mnu/MWBMAN020000"
        />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="케이뱅크(Kbank) - make money" />
        <meta
          property="og:description"
          content="우리는 모두 부자가 될 권리가 있다"
        />
        <meta
          property="og:image"
          content="https://m.kbanknow.com/resource/img/bim/Kbank_kakao_og.png"
        />

        <title>상품 - 케이뱅크</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <ProductTabCarousel tabList={tabList} newBdg={newBdg} />

      <Curating pdRcmdFavSvrList1={pdRcmdFavSvrList1} />

      <Popular pdRcmdFavSvrList2={pdRcmdFavSvrList2} />

      <Recommend pdRcmdFavSvrList3={pdRcmdFavSvrList3} />
    </Layout>
  )
}
